-- Dang Pest Control FAQ seed — 55 questions across 8 categories
-- Tenant ID: 1611b16f-381b-4d4f-ba3a-fbde56ad425b
-- Run: DELETE FROM faqs WHERE tenant_id = '1611b16f-381b-4d4f-ba3a-fbde56ad425b'; first

INSERT INTO faqs (tenant_id, question, answer, category, sort_order) VALUES

-- GENERAL (18)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What is a pest?', 'Basically, any unwanted animal or plant that typically has a negative effect on people and the surrounding environment.', 'General', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What is Integrated Pest Management (IPM)?', 'Integrated pest management (IPM) is a strategy that uses a variety of techniques to control pests without solely relying on pesticides. These prevention techniques include cultural practices, pesticides, exclusion, natural enemies and host resistance. The goal is to achieve long-term control of target pests with minimal impact on public health, non-target organisms and the environment.', 'General', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are you required to have a license?', 'Absolutely! All pest professionals must be licensed through the Texas Department of Agriculture. Anyone operating without a license is operating illegally.', 'General', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Is pest control kid and pet friendly?', 'Yes. Our primary concerns are our clients and the environment. All of our pest control chemicals are EPA approved, and we have been thoroughly trained on industry regulations and guidelines. We only use products according to the product labels that define the amount and locations where the products can be applied. Also, our Integrated Pest Management strategy gives us many ways to combat pests outside of the use of chemical products.', 'General', 4),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How often do you treat my property?', 'It depends but general pest treatments are typically every two to three months. Mosquito treatments are generally monthly. Termites, bed bugs, fleas and ticks, rodents, other pests, and infestations typically require an inspection to determine the best treatment plan and frequency.', 'General', 5),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How long does your treatment last?', 'It really depends what product is applied and where it is applied. Our custom treatment plans take into consideration the efficacy of the products and our warranty covers your property between treatments.', 'General', 6),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Does weather affect your treatments?', 'The weather can definitely affect the exterior treatments but not the interior treatments. We avoid doing many exterior treatments when it is rainy and/or windy. Many pesticides today are formulated with a coating that prevents them from washing away easily in rain, once they dry. We take weather conditions into account daily, prior to servicing our clients.', 'General', 7),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What can the property owner do to combat pests?', 'You can actually do a lot! Most importantly, you should keep your property clean of food and clutter (inside and outside). Keep your property clean and store food in sealed containers and remove debris that may be used as nesting material. Also, seal any access points such as gaps around doors and windows, weepholes, gaps around pipes and wires, holes in siding, roofs, etc. Make sure there are no leaking pipes or standing water inside or outside.', 'General', 8),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How much does pest control cost?', 'While many services can be quoted over the phone, it depends on the type of pest, severity of infestation and the size of your property. Contact our office for the most accurate information and cost of services.', 'General', 9),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What if I see pests between treatments?', 'Our warranty for general pest control states we will return and treat again between scheduled treatments...for free!', 'General', 10),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Do you offer a warranty?', 'We sure do and EVERY pest control company should as well. Our warranties vary depending on the type of pest and level of infestation and will be described in detail prior to scheduling any service.', 'General', 11),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why should I hire a pest control professional instead of doing it myself?', 'While taking things into your own hands may seem effective in some instances, pest control almost always requires more strategy and attention than the average person can give it. There is no "one size fits all" application and even different types of cockroaches will require different treatment strategies. More often than not, homeowners lack the knowledge and time to accurately devise an effective treatment plan.', 'General', 12),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How long does it take for the insecticide to work?', 'It really depends on the pest and the treatment. We pick the treatment that will give us the best long-term results while diminishing the pest population as quickly as possible. In the best case we will see pest mortality almost immediately while total control may take as several weeks and require a series of more frequent treatments. It is common to see a slight increase in pest activity right after our initial treatment. That means it''s working! While some treatments are designed to terminate the pest on contact, some repel them and some disrupt their life cycle so they can''t reproduce. A good pest professional should always evaluate the situation and develop the best plan for each job.', 'General', 13),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Does the inside or outside of your house smell after pest control treatments?', 'Way back in the "old days", you would definitely know your house was treated because of the strong chemical smell. Those days are long gone...thankfully! The products that Dang Pest Control uses have no significant odor or color. This allows for a more discreet application and reduces discomfort for residents in treated areas.', 'General', 14),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How are pests getting in my home?', 'There are numerous ways that pests can enter a home. Ants, roaches, other insects, and even mice and rats can enter through impossibly tiny cracks and crevices. They will also seek out the easiest path such as tree limbs, vines, gutters, etc. To decrease the access points, keep all landscaping trimmed away from the building, weatherproof around all windows, doors, weep holes, and other penetrations into the building. To lessen the chances of pests intruding into your home, be sure to keep any branches, shrubs, piles of firewood, decorative rocks, beds, and any other aspect of landscaping well-maintained.', 'General', 15),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why are pests in my house?', 'Primarily because they are attracted to readily available food sources, moisture, and shelter.', 'General', 16),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Will the products damage my floors or furniture?', 'No. They are water-based and used only in the correct quantities and locations to minimize any negative effects.', 'General', 17),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Should your pest control company be insured?', 'Yes, the pest control company you hire should be insured. Dang Pest Control is licensed and insured, and our technicians are highly trained.', 'General', 18),

-- ANTS (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why are ants so bad in East Texas?', 'East Texas humidity, pine trees, and long warm seasons create the perfect breeding ground for ants. In Tyler and surrounding communities, we commonly see fire ants, carpenter ants, and odorous house ants thriving almost year-round.', 'Ants', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are fire ants dangerous in Tyler yards?', 'Yes. Fire ants are extremely common in East Texas lawns and can deliver painful stings, especially to children and pets. Their mounds often appear after rainstorms, which we get plenty of here in the Piney Woods.', 'Ants', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why do ants keep coming back inside my home?', 'Ant colonies live outside but send scouts indoors for moisture and food. Because of East Texas humidity, ants can stay active most of the year. That''s why recurring pest control is the most effective solution.', 'Ants', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'When is ant season in East Texas?', 'While spring and summer are peak seasons, ants in Tyler can remain active nearly year-round due to mild winters.', 'Ants', 4),

-- SPIDERS (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are brown recluse spiders common in East Texas?', 'Yes. Brown recluse spiders are found throughout East Texas, including Tyler, especially in garages, attics, and storage areas.', 'Spiders', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why do I have so many spiders around my porch lights?', 'Spiders follow their food source. Porch lights attract insects, which attract spiders.', 'Spiders', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are black widows dangerous?', 'Black widows are present in East Texas and can deliver venomous bites. They prefer dark, undisturbed areas.', 'Spiders', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Do spider treatments eliminate webs?', 'Professional exterior treatments significantly reduce spider populations and web formation over time.', 'Spiders', 4),

-- WASPS & YELLOW JACKETS (5)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What types of wasps are common in East Texas?', 'In Tyler and surrounding East Texas communities, we most commonly see red paper wasps, yellow jackets, and hornets. Our long warm season allows wasp colonies to grow quickly from spring through late fall.', 'Wasps & Yellow Jackets', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why are red wasps so aggressive around my home?', 'Red wasps (very common in East Texas) build nests under eaves, porch ceilings, sheds, and play equipment. They become aggressive when they feel their nest is threatened — especially during late summer when colonies are at peak size.', 'Wasps & Yellow Jackets', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are yellow jackets different from regular wasps?', 'Yes. Yellow jackets often build nests underground or inside wall voids. In East Texas yards, they''re frequently disturbed during mowing or landscaping, which is when most stings occur.', 'Wasps & Yellow Jackets', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'When is wasp season in Tyler, TX?', 'Wasp activity typically begins in early spring (March/April) and peaks during hot East Texas summers. Because our winters are mild, queens can survive and rebuild nests year after year.', 'Wasps & Yellow Jackets', 4),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Can I remove a wasp nest myself?', 'We don''t recommend it. East Texas wasp species defend their nests aggressively and can sting multiple times. Professional removal ensures safe treatment and reduces the chance of re-nesting.', 'Wasps & Yellow Jackets', 5),

-- SCORPIONS (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are scorpions common in East Texas?', 'While more common in West Texas, scorpions — including Texas bark scorpions — are found in Tyler and surrounding wooded areas, especially near stacked wood and rock beds.', 'Scorpions', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'When are scorpions most active in Tyler?', 'Scorpions are most active during hot summer months but may seek shelter indoors during heavy rains or cooler weather shifts.', 'Scorpions', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are scorpion stings dangerous?', 'Most scorpion stings are painful but not life-threatening. However, children and pets may experience stronger reactions.', 'Scorpions', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How do scorpions get inside homes?', 'They squeeze through small foundation cracks, under doors, and around utility lines — common in older East Texas homes.', 'Scorpions', 4),

-- RODENTS (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are rodents common in East Texas homes?', 'Yes. Older homes in Tyler, crawl spaces, and wooded properties provide easy access points for mice and rats.', 'Rodents', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How small of an opening can a mouse fit through?', 'A mouse can squeeze through a hole the size of a dime. In East Texas homes with pier-and-beam foundations, this is especially common.', 'Rodents', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'When are rodents most active in Tyler?', 'Rodents seek shelter during colder months but can remain active year-round here due to mild winters.', 'Rodents', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What attracts rodents in the Piney Woods area?', 'Pet food, bird feeders, fallen pecans, and dense landscaping around homes are major attractants.', 'Rodents', 4),

-- MOSQUITOES (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why are mosquitoes so aggressive in East Texas?', 'Our heat, humidity, and frequent rain create ideal breeding conditions. Mosquitoes can lay eggs in as little as a bottle cap of standing water.', 'Mosquitoes', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'When does mosquito season start in Tyler?', 'Mosquito activity often begins as early as March and can last into November depending on temperatures.', 'Mosquitoes', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Do backyard treatments really work?', 'Yes. Targeted treatments significantly reduce adult mosquito populations and breeding areas. Ongoing treatments are especially effective during peak East Texas summer months.', 'Mosquitoes', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why do mosquitoes seem worse after a mild winter?', 'East Texas winters are often not cold enough to significantly reduce mosquito populations, allowing more to survive into spring.', 'Mosquitoes', 4),

-- FLEAS & TICKS (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why are fleas so bad in East Texas?', 'East Texas humidity creates ideal breeding conditions. Fleas reproduce rapidly in shaded yards and on pets.', 'Fleas & Ticks', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are ticks common in Tyler?', 'Yes. Ticks thrive in tall grass, wooded areas, and properties near the Piney Woods. They are active most of the year here.', 'Fleas & Ticks', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Can fleas live in my yard without pets?', 'Yes. Wildlife such as raccoons, squirrels, and stray animals can introduce fleas into East Texas yards.', 'Fleas & Ticks', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'When is flea and tick season in Tyler?', 'Peak activity runs from spring through fall, but mild winters allow survival year-round.', 'Fleas & Ticks', 4),

-- ROACHES (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'What types of roaches are common in East Texas?', 'In Tyler and surrounding East Texas areas, we frequently treat American cockroaches (also called palmetto bugs) and German cockroaches. The warm, humid climate makes it easy for them to survive.', 'Roaches', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Why am I seeing large roaches after rain?', 'Heavy East Texas rains drive roaches out of storm drains and into homes. They are moisture-seeking pests and thrive in humid environments.', 'Roaches', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Does seeing one roach mean I have an infestation?', 'Not always — but in East Texas, where roach populations are high, it''s often a sign that there are more nearby. German roaches especially multiply quickly indoors.', 'Roaches', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How can I prevent roaches in Tyler''s humid climate?', 'Regular perimeter treatments and moisture control are key. Because our humidity levels stay high most of the year, ongoing service is the best defense.', 'Roaches', 4),

-- BED BUGS (4)
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Are bed bugs common in East Texas?', 'Yes. Bed bugs are found in homes, apartments, hotels, and student housing throughout Tyler and East Texas.', 'Bed Bugs', 1),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How do bed bugs spread?', 'They travel on luggage, clothing, furniture, and through shared walls in apartments.', 'Bed Bugs', 2),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'Can I treat bed bugs myself?', 'DIY treatments often fail because bed bugs hide in mattress seams, wall voids, and furniture cracks. Professional treatment is strongly recommended.', 'Bed Bugs', 3),
('1611b16f-381b-4d4f-ba3a-fbde56ad425b', 'How quickly do bed bugs multiply?', 'Bed bugs reproduce quickly and can become a major infestation within weeks if untreated.', 'Bed Bugs', 4);
