// Default page_content rows for new tenant provisioning.
// Mirrors src/lib/pageDefaults.ts — keep in sync.

export function getPageContentRows(tenantId: string, businessName: string) {
  const name = businessName || 'Your Business'
  return [
    { tenant_id: tenantId, page_slug: 'home', title: `${name} — Professional Pest Control`, subtitle: 'Licensed & insured professionals. Fast, effective results.', intro: '', image_url: '/images/pests/pest_control.jpg' },
    { tenant_id: tenantId, page_slug: 'about', title: `About ${name}`, subtitle: 'Locally owned and operated.', intro: 'We are a locally owned pest control company dedicated to protecting homes and businesses with science-backed solutions, transparent pricing, and guaranteed results.', image_url: '/images/pests/tech_1.jpg' },
    { tenant_id: tenantId, page_slug: 'pest-control', title: 'General Pest Control', subtitle: 'One plan. All pests. Year-round protection.', intro: 'Our general pest control plans provide comprehensive protection against all common household pests with regular maintenance visits and a satisfaction guarantee.', image_url: '/images/pests/pest_control.jpg' },
    { tenant_id: tenantId, page_slug: 'termite-control', title: 'Termite Control', subtitle: 'Stop termites before they destroy your home.', intro: "East Texas's warm, humid climate makes it one of the highest-risk areas for termite damage. Our termite control program uses industry-leading treatments to eliminate colonies completely.", image_url: '/images/pests/termite_control.jpg' },
    { tenant_id: tenantId, page_slug: 'termite-inspections', title: 'Termite Inspections', subtitle: 'WDI reports for home sales — fast turnaround.', intro: 'A Wood-Destroying Insect (WDI) inspection is required for most real estate transactions in Texas. Our licensed inspectors provide thorough, certified WDI reports with fast turnaround.', image_url: '/images/pests/termite_inspection.jpg' },
    { tenant_id: tenantId, page_slug: 'roach-control', title: 'Cockroach Control', subtitle: 'Complete roach elimination — inside and out.', intro: 'Cockroaches spread bacteria, trigger allergies and asthma, and contaminate food. A single sighting usually means dozens more are hiding. We eliminate them completely.', image_url: '/images/pests/roach.jpg' },
    { tenant_id: tenantId, page_slug: 'ant-control', title: 'Ant Control', subtitle: 'Eliminate fire ants, carpenter ants, and more.', intro: 'From painful fire ant stings to carpenter ants destroying wood structure, ant infestations require professional treatment to fully eliminate. We handle all species.', image_url: '/images/pests/ant.jpg' },
    { tenant_id: tenantId, page_slug: 'mosquito-control', title: 'Mosquito Control', subtitle: 'Take back your yard — guaranteed mosquito reduction.', intro: 'Mosquitoes carry dangerous diseases including West Nile virus and Zika. Our professional mosquito control program significantly reduces mosquito populations on your property.', image_url: '/images/pests/Mosquito.jpg' },
    { tenant_id: tenantId, page_slug: 'bed-bug-control', title: 'Bed Bug Extermination', subtitle: 'Complete bed bug elimination — sleep tight again.', intro: 'Bed bugs are expert hitchhikers that hide in mattress seams, box springs, and furniture. Our heat and chemical treatments eliminate them at every life stage.', image_url: '/images/pests/bed_bug.jpg' },
    { tenant_id: tenantId, page_slug: 'flea-tick-control', title: 'Flea & Tick Control', subtitle: 'Protect your family and pets from fleas and ticks.', intro: 'Fleas and ticks transmit dangerous diseases including Lyme disease and Rocky Mountain spotted fever. We treat your home and yard to break the life cycle.', image_url: '/images/pests/flea_tik.jpg' },
    { tenant_id: tenantId, page_slug: 'rodent-control', title: 'Rodent Control', subtitle: 'Mice and rats eliminated — entry points sealed.', intro: 'Rodents chew electrical wires, contaminate food, and spread disease. We eliminate active infestations and seal entry points to prevent return.', image_url: '/images/pests/rodent.jpg' },
    { tenant_id: tenantId, page_slug: 'scorpion-control', title: 'Scorpion Control', subtitle: 'Protecting families from scorpion stings.', intro: 'Scorpions hide in shoes, bedding, and dark areas during the day, putting your family at risk of painful stings. Our targeted treatments keep them out.', image_url: '/images/pests/scorpion.jpg' },
    { tenant_id: tenantId, page_slug: 'contact', title: 'Contact Us', subtitle: "Have a question or need service? We're here to help.", intro: '', image_url: '' },
    { tenant_id: tenantId, page_slug: 'faq', title: 'Frequently Asked Questions', subtitle: 'Everything you need to know about our pest control services.', intro: '', image_url: '' },
    { tenant_id: tenantId, page_slug: 'quote', title: 'Get a Free Quote', subtitle: "Complete these 4 quick steps and we'll get back to you fast.", intro: '', image_url: '' },
  ]
}
