/**
 * DUPLICATED FROM src/lib/service-areas/normalize.ts
 * Do not edit this file directly. When updating normalization
 * logic, edit the src/ copy and mirror changes here.
 * Rationale: Deno module resolution in Supabase edge functions
 * cannot cross into src/.
 */

export type NormalizedCity = {
  city: string
  slug: string
  state: string
  isCounty: boolean
  raw: string
}

export type NormalizeResult = {
  accepted: NormalizedCity[]
  rejected: Array<{ raw: string; reason: string }>
}

const SAINT_WHITELIST = ['saint paul', 'saint jo', 'saint hedwig']

export function parseRawInput(input: string | string[] | null | undefined): string[] {
  if (input == null) return []
  if (Array.isArray(input)) return input.map((s: string) => s.trim()).filter(Boolean)
  return (input as string).split(',').map((s: string) => s.trim()).filter(Boolean)
}

export function normalizeCity(raw: string): NormalizedCity | { rejected: string } {
  let s = raw.trim().replace(/\s+/g, ' ')
  if (!s) return { rejected: 'empty' }
  if (s.length > 100) return { rejected: 'too_long' }
  s = s.replace(/\s+\d{5}(-\d{4})?$/, '').trim()
  s = s.replace(/\s*,?\s*(TX|Texas)\s*$/i, '').trim()
  if (!s) return { rejected: 'empty' }
  if (/^\d+$/.test(s)) return { rejected: 'numeric' }
  const isCounty = /\bcounty\b/i.test(s)
  s = s.replace(/^Ft\.?\s+/i, 'Fort ')
  const stMatch = s.match(/^St\.?\s+(.+)$/i)
  if (stMatch) {
    const candidate = 'Saint ' + stMatch[1]
    if (SAINT_WHITELIST.includes(candidate.toLowerCase())) {
      s = candidate
    }
  }
  s = s.replace(/^N\.\s+/i, 'North ')
  s = s.replace(/^S\.\s+/i, 'South ')
  s = s.replace(/^E\.\s+/i, 'East ')
  s = s.replace(/^W\.\s+/i, 'West ')
  const city = s
    .split(' ')
    .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ')
  const slugBase = city
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
  const slug = `${slugBase}-tx`
  return { city, slug, state: 'TX', isCounty, raw }
}

export function normalizeAll(input: string | string[] | null | undefined): NormalizeResult {
  const tokens = parseRawInput(input)
  const accepted: NormalizedCity[] = []
  const rejected: Array<{ raw: string; reason: string }> = []
  const seenSlugs = new Map<string, number>()

  for (const token of tokens) {
    const result = normalizeCity(token)
    if ('rejected' in result) {
      rejected.push({ raw: token, reason: result.rejected })
      continue
    }
    const existing = seenSlugs.get(result.slug)
    if (existing !== undefined) {
      accepted[existing] = result
    } else {
      seenSlugs.set(result.slug, accepted.length)
      accepted.push(result)
    }
  }

  return { accepted, rejected }
}

export function buildJsonbProjection(rows: Array<{ city: string; is_live: boolean }>): string[] {
  return rows
    .filter((r: { city: string; is_live: boolean }) => r.is_live)
    .map((r: { city: string; is_live: boolean }) => r.city)
    .sort((a: string, b: string) => a.localeCompare(b))
}
