export type GuideItemType = 'heading' | 'body' | 'bullet' | 'tip' | 'warn' | 'step'
export interface GuideItem { type: GuideItemType; text: string }
export interface GuideSection { title: string; items: GuideItem[] }

export const GUIDE_SECTIONS: Record<string, GuideSection> = {
  'sales-call': {
    title: 'What to Collect on the Sales Call',
    items: [
      { type: 'body',    text: 'Run through this list on every call. If a client doesn\'t have something handy, flag it for the intake form.' },
      { type: 'heading', text: 'Business Basics' },
      { type: 'bullet',  text: 'Business name (official, as on their license)' },
      { type: 'bullet',  text: 'Owner name' },
      { type: 'bullet',  text: 'Phone number — the one displayed on the live site' },
      { type: 'bullet',  text: 'Email — for lead notifications and login' },
      { type: 'bullet',  text: 'Full address' },
      { type: 'bullet',  text: 'Business hours' },
      { type: 'bullet',  text: 'Tagline — one sentence description' },
      { type: 'bullet',  text: 'Founded year' },
      { type: 'bullet',  text: 'Number of technicians' },
      { type: 'heading', text: 'Credentials' },
      { type: 'bullet',  text: 'State pest control license number' },
      { type: 'bullet',  text: 'Any certifications (QualityPro, etc.)' },
      { type: 'heading', text: 'Services & Areas' },
      { type: 'bullet',  text: 'Every city/town they serve — be specific, not "Dallas area"' },
      { type: 'bullet',  text: 'Every pest service they offer' },
      { type: 'heading', text: 'Online Presence' },
      { type: 'bullet',  text: 'Facebook page URL' },
      { type: 'bullet',  text: 'Instagram handle (optional)' },
      { type: 'bullet',  text: 'Google Business profile URL' },
      { type: 'heading', text: 'Deal Terms' },
      { type: 'bullet',  text: 'Setup fee amount agreed' },
      { type: 'bullet',  text: 'Subscription tier: Starter $149 / Grow $249 / Pro $349 / Elite $499' },
    ],
  },
  'shell-palette': {
    title: 'Shell & Palette Selection',
    items: [
      { type: 'heading', text: 'The Four Shells' },
      { type: 'step',    text: 'Modern Pro — Clean dark hero, bold type. Best for established companies wanting a premium look.' },
      { type: 'step',    text: 'Clean Friendly — Bright, light layouts, friendly fonts. Best for owner-operators and small family businesses.' },
      { type: 'step',    text: 'Bold Shield — Strong visuals, shield/badge motifs. Best for companies emphasizing guarantees and certifications.' },
      { type: 'step',    text: 'Nature Fresh — Earth tones, natural aesthetic. Best for eco-friendly or green pest control companies.' },
      { type: 'heading', text: 'Palette Tips' },
      { type: 'tip',     text: 'Match their truck wrap or logo colors if possible.' },
      { type: 'tip',     text: 'When in doubt: Modern Pro + Forest & Cream. Works for almost everyone.' },
      { type: 'body',    text: 'Ask: Do you want corporate/professional OR warm/approachable?' },
      { type: 'heading', text: 'CTA Button Text' },
      { type: 'bullet',  text: 'Get a Free Quote (default — works for most)' },
      { type: 'bullet',  text: 'Schedule a Free Inspection (if they push inspections)' },
      { type: 'bullet',  text: 'Call Us Now (if they prefer phone calls)' },
      { type: 'bullet',  text: 'Book Online Today (if they use online booking)' },
    ],
  },
  'prospect-fields': {
    title: 'Filling the Prospect Record',
    items: [
      { type: 'body',    text: 'Every field maps directly to the live site. Blank fields = placeholder text on launch.' },
      { type: 'heading', text: 'Critical Fields' },
      { type: 'bullet',  text: 'Business Name — exactly as it should appear on the site' },
      { type: 'bullet',  text: 'Phone — displayed in header, hero, and contact page' },
      { type: 'bullet',  text: 'Admin Email + Password — client\'s login credentials' },
      { type: 'bullet',  text: 'Shell and Palette — locks the site\'s look and feel' },
      { type: 'heading', text: 'Integrations' },
      { type: 'step',    text: 'Google Maps Embed URL: maps.google.com → Share → Embed a map → copy src URL from the iframe' },
      { type: 'step',    text: 'Google Place ID: developers.google.com/maps → Places → Place ID Finder → search business → copy ID' },
      { type: 'step',    text: 'Facebook Page ID: Facebook page → About → Page Transparency → Page ID' },
      { type: 'tip',     text: 'Integrations can be added after provisioning if needed — they don\'t block Create Site.' },
    ],
  },
  'invoice': {
    title: 'Plan & Payment Guide',
    items: [
      { type: 'heading', text: 'Pricing Reference' },
      { type: 'bullet',  text: 'Starter  — $149/mo  |  Setup: $500–$1,000' },
      { type: 'bullet',  text: 'Grow     — $249/mo  |  Setup: $1,000–$1,500' },
      { type: 'bullet',  text: 'Pro      — $349/mo  |  Setup: $2,000–$3,500' },
      { type: 'bullet',  text: 'Elite    — $499/mo  |  Setup: $4,000–$10,000' },
      { type: 'tip',     text: '"Most clients are on Grow — it hits the sweet spot of features and value."' },
      { type: 'tip',     text: 'Setup fee covers the build cost. Position it as a one-time investment, not a recurring charge.' },
      { type: 'heading', text: 'If They Push Back on Setup Fee' },
      { type: 'bullet',  text: '"We can look at waiving or reducing it depending on your timeline."' },
      { type: 'bullet',  text: 'Reducing fee is better than dropping a tier — keeps recurring revenue up.' },
      { type: 'heading', text: 'Generating the Invoice' },
      { type: 'step',    text: 'Select the tier and confirm the setup fee amount.' },
      { type: 'step',    text: 'Click Generate Invoice — a Stripe link is created and emailed to the client.' },
      { type: 'step',    text: 'Send the subscription link separately after invoice is paid.' },
      { type: 'warn',    text: 'Do not send the intake link until setup fee payment is confirmed.' },
      { type: 'heading', text: 'Confirming Payment' },
      { type: 'bullet',  text: 'Prospect status updates to Paid automatically via Stripe webhook.' },
      { type: 'bullet',  text: 'Or verify directly at dashboard.stripe.com.' },
    ],
  },
  'intake': {
    title: 'Sending the Intake Link',
    items: [
      { type: 'tip',     text: 'Send within 24 hours of payment confirmation — client is most engaged now.' },
      { type: 'step',    text: 'Click Send Intake Link in the prospect record.' },
      { type: 'step',    text: 'Client receives a unique email link to their 4-step intake form.' },
      { type: 'step',    text: 'Follow up by text or phone to confirm they received it.' },
      { type: 'heading', text: 'The 4 Intake Steps' },
      { type: 'bullet',  text: 'Step 1: Business basics (name, phone, address, hours, tagline)' },
      { type: 'bullet',  text: 'Step 2: Services and service areas' },
      { type: 'bullet',  text: 'Step 3: Online presence (Facebook, Instagram, Google)' },
      { type: 'bullet',  text: 'Step 4: Branding extras (logo upload, notes)' },
      { type: 'heading', text: 'Importing Intake Data' },
      { type: 'step',    text: 'Once client completes the form, click Import from Intake.' },
      { type: 'step',    text: 'Review all fields — manually fill any gaps.' },
      { type: 'step',    text: 'Click Save to confirm.' },
    ],
  },
  'pre-provision': {
    title: 'Pre-Provisioning Checklist',
    items: [
      { type: 'body',    text: 'All items below must be complete before clicking Create Site.' },
      { type: 'warn',    text: 'Once provisioned, the slug (subdomain) is locked in. Double-check the business name.' },
      { type: 'heading', text: 'Required' },
      { type: 'bullet',  text: 'Business Name' },
      { type: 'bullet',  text: 'Owner Name' },
      { type: 'bullet',  text: 'Phone Number' },
      { type: 'bullet',  text: 'Email Address' },
      { type: 'bullet',  text: 'Business Address' },
      { type: 'bullet',  text: 'Business Hours' },
      { type: 'bullet',  text: 'Shell selected' },
      { type: 'bullet',  text: 'Palette selected' },
      { type: 'bullet',  text: 'CTA Button Text' },
      { type: 'bullet',  text: 'At least one service area' },
      { type: 'bullet',  text: 'Admin Email set' },
      { type: 'bullet',  text: 'Admin Password set' },
      { type: 'bullet',  text: 'Setup fee marked as Paid' },
      { type: 'heading', text: 'Strongly Recommended' },
      { type: 'bullet',  text: 'Google Maps Embed URL' },
      { type: 'bullet',  text: 'Google Place ID' },
      { type: 'bullet',  text: 'Facebook Page ID' },
      { type: 'bullet',  text: 'Tagline, founded year, number of technicians' },
    ],
  },
  'provisioning': {
    title: 'Creating the Site',
    items: [
      { type: 'body',    text: 'Create Site builds the subdomain, loads all prospect data, activates the admin dashboard, CRM, blog, and SEO tools.' },
      { type: 'heading', text: 'Steps' },
      { type: 'step',    text: 'Complete the pre-provisioning checklist.' },
      { type: 'step',    text: 'Click Create Site.' },
      { type: 'step',    text: 'Wait 30–60 seconds — do not click again or navigate away.' },
      { type: 'step',    text: 'Success message shows the client\'s new subdomain URL.' },
      { type: 'heading', text: 'If It Fails' },
      { type: 'bullet',  text: 'Read the error — it usually says what\'s missing.' },
      { type: 'bullet',  text: 'Common causes: missing required field, slug conflict, admin email already in use.' },
      { type: 'warn',    text: 'If you see "Slug already exists" — adjust the business name or slug before retrying.' },
      { type: 'heading', text: 'Verify After Provisioning' },
      { type: 'step',    text: 'Visit the subdomain — confirm business name, phone, and address are correct.' },
      { type: 'step',    text: 'Click 2–3 service pages to confirm content loaded.' },
      { type: 'step',    text: 'Check the Contact page for hours and address.' },
    ],
  },
  'post-launch': {
    title: 'Post-Launch Steps',
    items: [
      { type: 'heading', text: 'Subscription' },
      { type: 'step',    text: 'Click Send Subscription Link in the prospect record.' },
      { type: 'step',    text: 'Client subscribes via Stripe secure checkout.' },
      { type: 'step',    text: 'Confirm subscription active before sending credentials.' },
      { type: 'warn',    text: 'Do not send credentials until subscription is confirmed.' },
      { type: 'heading', text: 'Credentials' },
      { type: 'step',    text: 'Click Send Credentials.' },
      { type: 'step',    text: 'Client receives admin email and temporary password.' },
      { type: 'step',    text: 'Walk them through their first login on the handoff call.' },
      { type: 'heading', text: 'Reveal Call Order' },
      { type: 'step',    text: 'Home page hero — let it speak for itself.' },
      { type: 'step',    text: 'Scroll to services — show 2–3 service pages.' },
      { type: 'step',    text: 'About page — name, founded year, team size.' },
      { type: 'step',    text: 'Contact page — phone, address, hours.' },
      { type: 'step',    text: 'Admin dashboard tour.' },
      { type: 'step',    text: 'End: "This is all yours — let me show you how to log in."' },
      { type: 'tip',     text: 'Lead with mobile view — most of their leads will find them on mobile.' },
    ],
  },
  'faq': {
    title: 'Common Client Questions',
    items: [
      { type: 'heading', text: 'Can I change my colors after launch?' },
      { type: 'body',    text: 'Yes — reach out and we can update the palette anytime. It applies site-wide immediately.' },
      { type: 'heading', text: 'Can I use my own domain?' },
      { type: 'body',    text: 'Yes. Custom domain setup is available — connect them with Scott. The subdomain stays active during transition.' },
      { type: 'heading', text: 'Can I add a service page for a pest not listed?' },
      { type: 'body',    text: 'Yes — contact us to scope it. Some additions are included in the tier, others may have a small one-time fee.' },
      { type: 'heading', text: 'Can I add team members to my account?' },
      { type: 'body',    text: 'Not self-service yet — contact us with the name and email and we\'ll set up access.' },
      { type: 'heading', text: 'How do I write a blog post?' },
      { type: 'body',    text: 'Admin dashboard → Blog → New Post → write, add photo, hit Publish. Goes live immediately.' },
      { type: 'heading', text: 'How do I see my leads?' },
      { type: 'body',    text: 'Admin dashboard → CRM. Every quote request shows name, phone, and what they need. Mark as contacted, booked, or closed.' },
      { type: 'heading', text: 'Will the site show up on Google?' },
      { type: 'body',    text: 'Yes — built for local SEO. Results take 4–8 weeks. More blog posts = faster ranking.' },
      { type: 'heading', text: 'What if I want to cancel?' },
      { type: 'body',    text: 'No long-term contracts. Site stays active through end of billing period. Just reach out.' },
    ],
  },
}
