import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })

  try {
    const { prospect_id } = await req.json()
    if (!prospect_id) {
      return new Response(JSON.stringify({ error: 'prospect_id required' }), { status: 400, headers: cors })
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    )

    const { data: prospect, error } = await supabase
      .from('prospects')
      .select('id, company_name, source_url, scraped_content, business_info, branding')
      .eq('id', prospect_id)
      .maybeSingle()

    if (error || !prospect) {
      return new Response(JSON.stringify({ error: 'Prospect not found' }), { status: 404, headers: cors })
    }

    const bi  = (prospect.business_info  || {}) as Record<string, string>
    const br  = (prospect.branding       || {}) as Record<string, string>
    const sc  = prospect.scraped_content  || {}

    const slug     = (prospect.company_name || 'company').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
    const filename = `${slug}-bolt-context.md`

    const lines: string[] = []

    lines.push(`# ${prospect.company_name || 'Company'} — Site Context for Bolt`)
    lines.push('')
    lines.push('Generated by PestFlow Pro for custom site build.')
    lines.push(`Source: ${prospect.source_url || 'N/A'}`)
    lines.push('')

    lines.push('## Business Info')
    lines.push(`- Name: ${prospect.company_name || 'N/A'}`)
    if (bi.phone)    lines.push(`- Phone: ${bi.phone}`)
    if (bi.address)  lines.push(`- Address: ${bi.address}`)
    if (bi.tagline)  lines.push(`- Tagline: ${bi.tagline}`)
    lines.push('')

    lines.push('## Brand Colors')
    lines.push(`- Primary: ${br.primary_color || sc.primary_color || '#10b981'}`)
    lines.push(`- Accent:  ${br.accent_color  || sc.accent_color  || '#f5c518'}`)
    lines.push('')

    lines.push('## Site Structure (from scrape)')
    const pages = Array.isArray(sc) ? sc : (sc.pages || [])
    if (pages.length > 0) {
      for (const page of pages) {
        lines.push(`### ${page.slug || page.url || 'page'}`)
        if (page.title)    lines.push(`Title: ${page.title}`)
        if (page.subtitle) lines.push(`Subtitle: ${page.subtitle}`)
        if (page.intro)    lines.push(`Intro: ${page.intro}`)
        if (page.content)  lines.push(`Content: ${page.content}`)
        lines.push('')
      }
    } else {
      lines.push('### Home')
      if ((sc as any).tagline)     lines.push(`Subtitle: ${(sc as any).tagline}`)
      if ((sc as any).about_intro) lines.push(`Intro: ${(sc as any).about_intro}`)
      if ((sc as any).services)    lines.push(`Services: ${Array.isArray((sc as any).services) ? (sc as any).services.join(', ') : (sc as any).services}`)
      lines.push('')
    }

    lines.push('## Design Notes')
    const trustParts = [
      bi.founded_year && `${bi.founded_year} founded`,
      bi.certifications,
      bi.license,
    ].filter(Boolean)
    lines.push(`- Key trust signals: ${trustParts.length ? trustParts.join(', ') : 'none extracted'}`)
    lines.push('')

    lines.push('## Bolt Build Instructions')
    lines.push('Build a pest control website that closely matches the source site above.')
    lines.push('')
    lines.push('Requirements:')
    lines.push('- React + TypeScript + Tailwind CSS')
    lines.push('- Match the color scheme exactly')
    lines.push('- Match the navigation structure and section order')
    lines.push('- Use the exact copy from the Site Structure section above')
    lines.push('- Include all service pages listed')
    lines.push('- Mobile responsive')
    lines.push('- Connect to Supabase for content management')
    lines.push('- Deploy-ready on Vercel')

    const markdown = lines.join('\n')

    return new Response(JSON.stringify({ success: true, markdown, filename }), {
      headers: { ...cors, 'Content-Type': 'application/json' },
    })
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), { status: 500, headers: cors })
  }
})
