// Supabase Edge Function: package-claude-context
// Reads prospect + scraped data, calls Claude to extract structured business info,
// then returns a CLIENT_BRIEF.md and a BUILD_PROMPT.txt for IT to run in Codespaces.
//
// Deploy: supabase functions deploy package-claude-context --no-verify-jwt --project-ref biezzykcgzkrwdgqpsar

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Serialize JSONB scraped_content to text for Claude
function scrapedToText(sc: any): string {
  if (!sc || typeof sc !== 'object') return ''
  const lines: string[] = []
  if (sc.tagline)     lines.push(`Tagline: ${sc.tagline}`)
  if (sc.about_intro) lines.push(`About: ${sc.about_intro}`)
  if (sc.services)    lines.push(`Services: ${Array.isArray(sc.services) ? sc.services.join(', ') : sc.services}`)
  if (sc.phone)       lines.push(`Phone: ${sc.phone}`)
  if (sc.address)     lines.push(`Address: ${sc.address}`)
  if (sc.hours)       lines.push(`Hours: ${sc.hours}`)
  if (Array.isArray(sc.pages)) {
    for (const page of sc.pages) {
      lines.push(`\n## ${page.slug || page.url || 'page'}`)
      if (page.title)   lines.push(`Title: ${page.title}`)
      if (page.content) lines.push(String(page.content).slice(0, 2000))
    }
  }
  return lines.join('\n')
}

function buildBrief(extracted: any, prospect: any): string {
  const addr = [extracted.address, extracted.city, extracted.state, extracted.zip].filter(Boolean).join(', ')
  const lines = [
    `# ${extracted.business_name || prospect.company_name} — Client Brief`,
    `Generated by PestFlow Pro package-claude-context`,
    '',
    '## Overview',
    `- **Business:** ${extracted.business_name || prospect.company_name}`,
    `- **Tagline:** ${extracted.tagline || '—'}`,
    `- **Hero Headline:** ${extracted.hero_headline || '—'}`,
    `- **Phone:** ${extracted.phone || prospect.phone || '—'}`,
    `- **Email:** ${extracted.email || prospect.email || '—'}`,
    `- **Address:** ${addr || '—'}`,
    `- **Founded:** ${extracted.founded_year || '—'}`,
    `- **Tone:** ${extracted.tone || '—'}`,
    `- **Primary Color Guess:** ${extracted.primary_color_guess || '—'}`,
    '',
    `## Services (${(extracted.services || []).length})`,
    ...(extracted.services || []).map((s: any) => `- **${s.name}**: ${s.description}`),
    '',
    `## Service Areas`,
    (extracted.service_areas || []).join(', ') || '—',
    '',
    `## Team (${(extracted.team_members || []).length})`,
    ...(extracted.team_members || []).map((t: any) => `- **${t.name}** (${t.title}): ${t.bio}`),
    '',
    '## Trust Badges',
    (extracted.trust_badges || []).join(', ') || '—',
    '',
    `## Testimonials (${(extracted.testimonials || []).length})`,
    ...(extracted.testimonials || []).map((t: any) => `> "${t.text}" — ${t.author}`),
    '',
    '## Still Needs Manual Input',
    '- [ ] Google Place ID (for reviews)',
    '- [ ] Facebook Page ID + Access Token',
    '- [ ] Final color verification with client',
    '- [ ] Logo file (SVG preferred)',
    '- [ ] Domain configuration in Vercel',
  ]
  return lines.join('\n')
}

function buildPrompt(extracted: any, prospect: any, clientSlug: string): string {
  const name = extracted.business_name || prospect.company_name || 'Company'
  const safeName = name.replace(/[^A-Za-z0-9]/g, '')
  const addr = [extracted.address, extracted.city, extracted.state, extracted.zip].filter(Boolean).join(', ')
  const servicesList = (extracted.services || [])
    .map((s: any) => `- ${s.name}: ${s.description}`).join('\n') || '- (none extracted)'
  const teamList = (extracted.team_members || [])
    .map((t: any) => `- ${t.name}, ${t.title}: ${t.bio}`).join('\n') || '- (none extracted)'
  const testimonialsList = (extracted.testimonials || [])
    .map((t: any) => `- "${t.text}" — ${t.author} (${t.rating}/5)`).join('\n') || '- (none extracted)'
  const primaryColor = extracted.primary_color_guess || '#10b981'

  return `PESTFLOW PRO — FULL CUSTOM SHELL: ${name}
Read CLAUDE.md and SKILL.md before starting.
Work directly on main. One commit per task. No context file.

=== CLIENT ===
Business: ${name}
Slug: ${clientSlug}
Phone: ${extracted.phone || prospect.phone || '—'}
Email: ${extracted.email || prospect.email || '—'}
Address: ${addr || '—'}
Tagline: ${extracted.tagline || '—'}
Hero Headline: ${extracted.hero_headline || '—'}
Primary Color: ${primaryColor} (verify with client — this is a guess from scrape)
Tone: ${extracted.tone || 'professional'}
Service Areas: ${(extracted.service_areas || []).join(', ') || '—'}

=== TASK 1 — Create Shell Directory ===

Create src/shells/${clientSlug}/ with these files:
- index.ts (exports all components)
- ShellNav.tsx
- ShellHero.tsx
- ShellServices.tsx
- ShellAbout.tsx
- ShellFooter.tsx
- ShellPage.tsx (main shell assembler)

Follow ALL patterns from src/shells/modern-pro/ as the reference.
CSS custom properties for all brand colors (no hardcoded hex).
Files under 200 lines each. Split if needed.
Use the SAME CSS variable names as other shells:
  --color-primary, --color-accent, --color-bg-hero, --color-nav-bg, etc.

=== TASK 2 — Populate with Real Content ===

Use this extracted content (do not use placeholder text anywhere):

SERVICES (${(extracted.services || []).length} total):
${servicesList}

ABOUT COPY:
${extracted.about_copy || '(not extracted — write based on business name and services)'}

TEAM MEMBERS:
${teamList}

TRUST BADGES: ${(extracted.trust_badges || []).join(', ') || '(none extracted)'}

TESTIMONIALS:
${testimonialsList}

=== TASK 3 — Register Shell ===

In src/lib/shellThemes.ts:
- Add '${clientSlug}' to the shell type union
- Add default theme values using the extracted primary color: ${primaryColor}

In src/lib/SlugRouter.tsx (or wherever shells are resolved):
- Add case '${clientSlug}': return <${safeName}Shell />

=== TASK 4 — Seed Tenant Content ===

The tenant has already been provisioned with slug '${clientSlug}'.
Seed page_content rows for this tenant using the extracted content.

Use the Supabase service role client (already available in the codebase).
Upsert into page_content for pages: home, about, pest-control, contact.

=== TASK 5 — Commit and Verify ===

After all tasks:
git add . && git commit -m "feat(${clientSlug}): full custom shell from scrape" && git push

Verify build passes. Report any TypeScript errors.`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })

  try {
    const body = await req.json()
    const { prospect_id, scrape_markdown, client_slug } = body

    if (!prospect_id) {
      return new Response(JSON.stringify({ error: 'prospect_id required' }), { status: 400, headers: cors })
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    )

    const { data: prospect, error } = await supabase
      .from('prospects')
      .select('id, company_name, contact_name, email, phone, slug, build_path, custom_scope_notes, business_info, branding, source_url, scraped_content')
      .eq('id', prospect_id)
      .maybeSingle()

    if (error || !prospect) {
      return new Response(JSON.stringify({ error: 'Prospect not found' }), { status: 404, headers: cors })
    }

    const slug = client_slug || prospect.slug ||
      (prospect.company_name || 'company').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

    // Build context text for Claude: prefer explicit markdown, fall back to scraped_content JSONB
    const rawText = scrape_markdown || scrapedToText(prospect.scraped_content)
    if (!rawText.trim()) {
      return new Response(JSON.stringify({ error: 'No scrape data available. Run Firecrawl scrape first.' }), {
        status: 400, headers: cors,
      })
    }

    const extractionPrompt = `You are extracting structured business data from a pest control company website scrape.
Return ONLY valid JSON, no markdown, no preamble.

Extract:
{
  "business_name": "",
  "tagline": "",
  "hero_headline": "",
  "hero_subheadline": "",
  "phone": "",
  "email": "",
  "address": "",
  "city": "",
  "state": "",
  "zip": "",
  "service_areas": [],
  "services": [{"name": "", "description": "", "slug": ""}],
  "about_copy": "",
  "founded_year": "",
  "team_members": [{"name": "", "title": "", "bio": ""}],
  "primary_color_guess": "",
  "tone": "professional|friendly|bold|rustic",
  "trust_badges": [],
  "testimonials": [{"text": "", "author": "", "rating": 5}]
}

Scrape content:
${rawText.slice(0, 12000)}`

    const aiRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': Deno.env.get('ANTHROPIC_API_KEY')!,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 4096,
        messages: [{ role: 'user', content: extractionPrompt }],
      }),
    })

    const aiData = await aiRes.json()
    const rawJson = (aiData.content?.[0]?.text || '').replace(/```json|```/g, '').trim()
    let extracted: any = {}
    try { extracted = JSON.parse(rawJson) } catch { extracted = {} }

    const brief  = buildBrief(extracted, prospect)
    const prompt = buildPrompt(extracted, prospect, slug)

    return new Response(JSON.stringify({ brief, prompt, extracted }), {
      headers: { ...cors, 'Content-Type': 'application/json' },
    })
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), { status: 500, headers: cors })
  }
})
