-- ⚠️ SUPERSEDED by 20260624180000_s273_collapse_check_tenant_access_single_integer.sql.
-- NEUTRALIZED — NO-OP. This migration originally ADDED an additive integer overload of
-- public.check_tenant_access ALONGSIDE the original smallint signature (20260612144629).
-- Having both signatures present is exactly the PGRST203 ambiguity the collapse migration
-- (20260624180000) exists to fix: PostgREST resolves RPCs by parameter NAME, not type, so a
-- JSON-number argument could not choose between check_tenant_access(uuid, smallint) and
-- check_tenant_access(uuid, integer).
--
-- WHY NEUTRALIZED (not just re-ordered): relying on timestamp ordering alone is fragile. A
-- from-zero replay, an out-of-order apply, a cherry-pick, or a partial replay that stops
-- after this file but before 20260624180000 would re-introduce the second overload and bring
-- back PGRST203. By making this migration a no-op, the on-disk migration set yields EXACTLY
-- ONE check_tenant_access overload (the integer one created by 20260624180000) regardless of
-- replay order or which subset of migrations is applied.
--
-- The file is intentionally LEFT IN PLACE (not deleted) so its schema_migrations ledger row
-- and the historical trail remain intact. The DDL that added the second overload has been
-- removed; the canonical single integer-typed function is defined solely by 20260624180000.
--
-- Live DB is already in the correct single-overload state; this only fixes the repo trail.

SELECT 1;
